repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: ^backend/
      - id: end-of-file-fixer
        files: ^backend/
      - id: check-yaml
        files: ^backend/
      - id: check-toml
        files: ^backend/
      - id: check-merge-conflict
        files: ^backend/
      - id: check-added-large-files
        files: ^backend/
        args: ["--maxkb=500"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^backend/
      - id: ruff-format
        files: ^backend/
